[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1_000
evm_version = "shanghai"
block_gas_limit = 30_000_000
fs_permissions = [{ access = "read", path = "./test/fixtures"}]

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
